language: android

jdk:
  - oraclejdk7

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository

before_install:
 - chmod +x gradlew

script:
  - ./gradlew clean test check